# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fabio/Documents/VJ3D

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fabio/Documents/VJ3D

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fabio/Documents/VJ3D/CMakeFiles /home/fabio/Documents/VJ3D/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fabio/Documents/VJ3D/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CrossyRoad

# Build rule for target.
CrossyRoad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CrossyRoad
.PHONY : CrossyRoad

# fast build rule for target.
CrossyRoad/fast:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/build
.PHONY : CrossyRoad/fast

Animation3D.o: Animation3D.cpp.o

.PHONY : Animation3D.o

# target to build an object file
Animation3D.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Animation3D.cpp.o
.PHONY : Animation3D.cpp.o

Animation3D.i: Animation3D.cpp.i

.PHONY : Animation3D.i

# target to preprocess a source file
Animation3D.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Animation3D.cpp.i
.PHONY : Animation3D.cpp.i

Animation3D.s: Animation3D.cpp.s

.PHONY : Animation3D.s

# target to generate assembly for a file
Animation3D.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Animation3D.cpp.s
.PHONY : Animation3D.cpp.s

Button.o: Button.cpp.o

.PHONY : Button.o

# target to build an object file
Button.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Button.cpp.o
.PHONY : Button.cpp.o

Button.i: Button.cpp.i

.PHONY : Button.i

# target to preprocess a source file
Button.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Button.cpp.i
.PHONY : Button.cpp.i

Button.s: Button.cpp.s

.PHONY : Button.s

# target to generate assembly for a file
Button.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Button.cpp.s
.PHONY : Button.cpp.s

CsvReader.o: CsvReader.cpp.o

.PHONY : CsvReader.o

# target to build an object file
CsvReader.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/CsvReader.cpp.o
.PHONY : CsvReader.cpp.o

CsvReader.i: CsvReader.cpp.i

.PHONY : CsvReader.i

# target to preprocess a source file
CsvReader.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/CsvReader.cpp.i
.PHONY : CsvReader.cpp.i

CsvReader.s: CsvReader.cpp.s

.PHONY : CsvReader.s

# target to generate assembly for a file
CsvReader.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/CsvReader.cpp.s
.PHONY : CsvReader.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Game.cpp.s
.PHONY : Game.cpp.s

Level.o: Level.cpp.o

.PHONY : Level.o

# target to build an object file
Level.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Level.cpp.o
.PHONY : Level.cpp.o

Level.i: Level.cpp.i

.PHONY : Level.i

# target to preprocess a source file
Level.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Level.cpp.i
.PHONY : Level.cpp.i

Level.s: Level.cpp.s

.PHONY : Level.s

# target to generate assembly for a file
Level.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Level.cpp.s
.PHONY : Level.cpp.s

LevelGenerator.o: LevelGenerator.cpp.o

.PHONY : LevelGenerator.o

# target to build an object file
LevelGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/LevelGenerator.cpp.o
.PHONY : LevelGenerator.cpp.o

LevelGenerator.i: LevelGenerator.cpp.i

.PHONY : LevelGenerator.i

# target to preprocess a source file
LevelGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/LevelGenerator.cpp.i
.PHONY : LevelGenerator.cpp.i

LevelGenerator.s: LevelGenerator.cpp.s

.PHONY : LevelGenerator.s

# target to generate assembly for a file
LevelGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/LevelGenerator.cpp.s
.PHONY : LevelGenerator.cpp.s

Mesh.o: Mesh.cpp.o

.PHONY : Mesh.o

# target to build an object file
Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Mesh.cpp.o
.PHONY : Mesh.cpp.o

Mesh.i: Mesh.cpp.i

.PHONY : Mesh.i

# target to preprocess a source file
Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Mesh.cpp.i
.PHONY : Mesh.cpp.i

Mesh.s: Mesh.cpp.s

.PHONY : Mesh.s

# target to generate assembly for a file
Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Mesh.cpp.s
.PHONY : Mesh.cpp.s

Model.o: Model.cpp.o

.PHONY : Model.o

# target to build an object file
Model.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Model.cpp.o
.PHONY : Model.cpp.o

Model.i: Model.cpp.i

.PHONY : Model.i

# target to preprocess a source file
Model.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Model.cpp.i
.PHONY : Model.cpp.i

Model.s: Model.cpp.s

.PHONY : Model.s

# target to generate assembly for a file
Model.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Model.cpp.s
.PHONY : Model.cpp.s

ModelAnimated.o: ModelAnimated.cpp.o

.PHONY : ModelAnimated.o

# target to build an object file
ModelAnimated.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ModelAnimated.cpp.o
.PHONY : ModelAnimated.cpp.o

ModelAnimated.i: ModelAnimated.cpp.i

.PHONY : ModelAnimated.i

# target to preprocess a source file
ModelAnimated.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ModelAnimated.cpp.i
.PHONY : ModelAnimated.cpp.i

ModelAnimated.s: ModelAnimated.cpp.s

.PHONY : ModelAnimated.s

# target to generate assembly for a file
ModelAnimated.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ModelAnimated.cpp.s
.PHONY : ModelAnimated.cpp.s

ObjReader.o: ObjReader.cpp.o

.PHONY : ObjReader.o

# target to build an object file
ObjReader.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObjReader.cpp.o
.PHONY : ObjReader.cpp.o

ObjReader.i: ObjReader.cpp.i

.PHONY : ObjReader.i

# target to preprocess a source file
ObjReader.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObjReader.cpp.i
.PHONY : ObjReader.cpp.i

ObjReader.s: ObjReader.cpp.s

.PHONY : ObjReader.s

# target to generate assembly for a file
ObjReader.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObjReader.cpp.s
.PHONY : ObjReader.cpp.s

Obstacle.o: Obstacle.cpp.o

.PHONY : Obstacle.o

# target to build an object file
Obstacle.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Obstacle.cpp.o
.PHONY : Obstacle.cpp.o

Obstacle.i: Obstacle.cpp.i

.PHONY : Obstacle.i

# target to preprocess a source file
Obstacle.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Obstacle.cpp.i
.PHONY : Obstacle.cpp.i

Obstacle.s: Obstacle.cpp.s

.PHONY : Obstacle.s

# target to generate assembly for a file
Obstacle.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Obstacle.cpp.s
.PHONY : Obstacle.cpp.s

ObstacleBonus.o: ObstacleBonus.cpp.o

.PHONY : ObstacleBonus.o

# target to build an object file
ObstacleBonus.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleBonus.cpp.o
.PHONY : ObstacleBonus.cpp.o

ObstacleBonus.i: ObstacleBonus.cpp.i

.PHONY : ObstacleBonus.i

# target to preprocess a source file
ObstacleBonus.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleBonus.cpp.i
.PHONY : ObstacleBonus.cpp.i

ObstacleBonus.s: ObstacleBonus.cpp.s

.PHONY : ObstacleBonus.s

# target to generate assembly for a file
ObstacleBonus.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleBonus.cpp.s
.PHONY : ObstacleBonus.cpp.s

ObstacleSpawner.o: ObstacleSpawner.cpp.o

.PHONY : ObstacleSpawner.o

# target to build an object file
ObstacleSpawner.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleSpawner.cpp.o
.PHONY : ObstacleSpawner.cpp.o

ObstacleSpawner.i: ObstacleSpawner.cpp.i

.PHONY : ObstacleSpawner.i

# target to preprocess a source file
ObstacleSpawner.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleSpawner.cpp.i
.PHONY : ObstacleSpawner.cpp.i

ObstacleSpawner.s: ObstacleSpawner.cpp.s

.PHONY : ObstacleSpawner.s

# target to generate assembly for a file
ObstacleSpawner.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleSpawner.cpp.s
.PHONY : ObstacleSpawner.cpp.s

Particle.o: Particle.cpp.o

.PHONY : Particle.o

# target to build an object file
Particle.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Particle.cpp.o
.PHONY : Particle.cpp.o

Particle.i: Particle.cpp.i

.PHONY : Particle.i

# target to preprocess a source file
Particle.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Particle.cpp.i
.PHONY : Particle.cpp.i

Particle.s: Particle.cpp.s

.PHONY : Particle.s

# target to generate assembly for a file
Particle.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Particle.cpp.s
.PHONY : Particle.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Player.cpp.s
.PHONY : Player.cpp.s

ResourceManager.o: ResourceManager.cpp.o

.PHONY : ResourceManager.o

# target to build an object file
ResourceManager.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ResourceManager.cpp.o
.PHONY : ResourceManager.cpp.o

ResourceManager.i: ResourceManager.cpp.i

.PHONY : ResourceManager.i

# target to preprocess a source file
ResourceManager.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ResourceManager.cpp.i
.PHONY : ResourceManager.cpp.i

ResourceManager.s: ResourceManager.cpp.s

.PHONY : ResourceManager.s

# target to generate assembly for a file
ResourceManager.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ResourceManager.cpp.s
.PHONY : ResourceManager.cpp.s

Scene.o: Scene.cpp.o

.PHONY : Scene.o

# target to build an object file
Scene.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Scene.cpp.o
.PHONY : Scene.cpp.o

Scene.i: Scene.cpp.i

.PHONY : Scene.i

# target to preprocess a source file
Scene.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Scene.cpp.i
.PHONY : Scene.cpp.i

Scene.s: Scene.cpp.s

.PHONY : Scene.s

# target to generate assembly for a file
Scene.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Scene.cpp.s
.PHONY : Scene.cpp.s

SceneDead.o: SceneDead.cpp.o

.PHONY : SceneDead.o

# target to build an object file
SceneDead.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneDead.cpp.o
.PHONY : SceneDead.cpp.o

SceneDead.i: SceneDead.cpp.i

.PHONY : SceneDead.i

# target to preprocess a source file
SceneDead.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneDead.cpp.i
.PHONY : SceneDead.cpp.i

SceneDead.s: SceneDead.cpp.s

.PHONY : SceneDead.s

# target to generate assembly for a file
SceneDead.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneDead.cpp.s
.PHONY : SceneDead.cpp.s

SceneMenu.o: SceneMenu.cpp.o

.PHONY : SceneMenu.o

# target to build an object file
SceneMenu.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneMenu.cpp.o
.PHONY : SceneMenu.cpp.o

SceneMenu.i: SceneMenu.cpp.i

.PHONY : SceneMenu.i

# target to preprocess a source file
SceneMenu.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneMenu.cpp.i
.PHONY : SceneMenu.cpp.i

SceneMenu.s: SceneMenu.cpp.s

.PHONY : SceneMenu.s

# target to generate assembly for a file
SceneMenu.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneMenu.cpp.s
.PHONY : SceneMenu.cpp.s

SceneTest.o: SceneTest.cpp.o

.PHONY : SceneTest.o

# target to build an object file
SceneTest.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneTest.cpp.o
.PHONY : SceneTest.cpp.o

SceneTest.i: SceneTest.cpp.i

.PHONY : SceneTest.i

# target to preprocess a source file
SceneTest.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneTest.cpp.i
.PHONY : SceneTest.cpp.i

SceneTest.s: SceneTest.cpp.s

.PHONY : SceneTest.s

# target to generate assembly for a file
SceneTest.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneTest.cpp.s
.PHONY : SceneTest.cpp.s

SceneWin.o: SceneWin.cpp.o

.PHONY : SceneWin.o

# target to build an object file
SceneWin.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneWin.cpp.o
.PHONY : SceneWin.cpp.o

SceneWin.i: SceneWin.cpp.i

.PHONY : SceneWin.i

# target to preprocess a source file
SceneWin.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneWin.cpp.i
.PHONY : SceneWin.cpp.i

SceneWin.s: SceneWin.cpp.s

.PHONY : SceneWin.s

# target to generate assembly for a file
SceneWin.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneWin.cpp.s
.PHONY : SceneWin.cpp.s

Shader.o: Shader.cpp.o

.PHONY : Shader.o

# target to build an object file
Shader.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Shader.cpp.o
.PHONY : Shader.cpp.o

Shader.i: Shader.cpp.i

.PHONY : Shader.i

# target to preprocess a source file
Shader.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Shader.cpp.i
.PHONY : Shader.cpp.i

Shader.s: Shader.cpp.s

.PHONY : Shader.s

# target to generate assembly for a file
Shader.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Shader.cpp.s
.PHONY : Shader.cpp.s

ShaderProgram.o: ShaderProgram.cpp.o

.PHONY : ShaderProgram.o

# target to build an object file
ShaderProgram.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ShaderProgram.cpp.o
.PHONY : ShaderProgram.cpp.o

ShaderProgram.i: ShaderProgram.cpp.i

.PHONY : ShaderProgram.i

# target to preprocess a source file
ShaderProgram.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ShaderProgram.cpp.i
.PHONY : ShaderProgram.cpp.i

ShaderProgram.s: ShaderProgram.cpp.s

.PHONY : ShaderProgram.s

# target to generate assembly for a file
ShaderProgram.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ShaderProgram.cpp.s
.PHONY : ShaderProgram.cpp.s

Sprite.o: Sprite.cpp.o

.PHONY : Sprite.o

# target to build an object file
Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Sprite.cpp.o
.PHONY : Sprite.cpp.o

Sprite.i: Sprite.cpp.i

.PHONY : Sprite.i

# target to preprocess a source file
Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Sprite.cpp.i
.PHONY : Sprite.cpp.i

Sprite.s: Sprite.cpp.s

.PHONY : Sprite.s

# target to generate assembly for a file
Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Sprite.cpp.s
.PHONY : Sprite.cpp.s

Text.o: Text.cpp.o

.PHONY : Text.o

# target to build an object file
Text.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Text.cpp.o
.PHONY : Text.cpp.o

Text.i: Text.cpp.i

.PHONY : Text.i

# target to preprocess a source file
Text.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Text.cpp.i
.PHONY : Text.cpp.i

Text.s: Text.cpp.s

.PHONY : Text.s

# target to generate assembly for a file
Text.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Text.cpp.s
.PHONY : Text.cpp.s

Text3D.o: Text3D.cpp.o

.PHONY : Text3D.o

# target to build an object file
Text3D.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Text3D.cpp.o
.PHONY : Text3D.cpp.o

Text3D.i: Text3D.cpp.i

.PHONY : Text3D.i

# target to preprocess a source file
Text3D.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Text3D.cpp.i
.PHONY : Text3D.cpp.i

Text3D.s: Text3D.cpp.s

.PHONY : Text3D.s

# target to generate assembly for a file
Text3D.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Text3D.cpp.s
.PHONY : Text3D.cpp.s

Texture.o: Texture.cpp.o

.PHONY : Texture.o

# target to build an object file
Texture.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Texture.cpp.o
.PHONY : Texture.cpp.o

Texture.i: Texture.cpp.i

.PHONY : Texture.i

# target to preprocess a source file
Texture.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Texture.cpp.i
.PHONY : Texture.cpp.i

Texture.s: Texture.cpp.s

.PHONY : Texture.s

# target to generate assembly for a file
Texture.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Texture.cpp.s
.PHONY : Texture.cpp.s

TexturedQuad.o: TexturedQuad.cpp.o

.PHONY : TexturedQuad.o

# target to build an object file
TexturedQuad.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/TexturedQuad.cpp.o
.PHONY : TexturedQuad.cpp.o

TexturedQuad.i: TexturedQuad.cpp.i

.PHONY : TexturedQuad.i

# target to preprocess a source file
TexturedQuad.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/TexturedQuad.cpp.i
.PHONY : TexturedQuad.cpp.i

TexturedQuad.s: TexturedQuad.cpp.s

.PHONY : TexturedQuad.s

# target to generate assembly for a file
TexturedQuad.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/TexturedQuad.cpp.s
.PHONY : TexturedQuad.cpp.s

Tile.o: Tile.cpp.o

.PHONY : Tile.o

# target to build an object file
Tile.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Tile.cpp.o
.PHONY : Tile.cpp.o

Tile.i: Tile.cpp.i

.PHONY : Tile.i

# target to preprocess a source file
Tile.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Tile.cpp.i
.PHONY : Tile.cpp.i

Tile.s: Tile.cpp.s

.PHONY : Tile.s

# target to generate assembly for a file
Tile.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Tile.cpp.s
.PHONY : Tile.cpp.s

Tilemap.o: Tilemap.cpp.o

.PHONY : Tilemap.o

# target to build an object file
Tilemap.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Tilemap.cpp.o
.PHONY : Tilemap.cpp.o

Tilemap.i: Tilemap.cpp.i

.PHONY : Tilemap.i

# target to preprocess a source file
Tilemap.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Tilemap.cpp.i
.PHONY : Tilemap.cpp.i

Tilemap.s: Tilemap.cpp.s

.PHONY : Tilemap.s

# target to generate assembly for a file
Tilemap.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Tilemap.cpp.s
.PHONY : Tilemap.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CrossyRoad"
	@echo "... Animation3D.o"
	@echo "... Animation3D.i"
	@echo "... Animation3D.s"
	@echo "... Button.o"
	@echo "... Button.i"
	@echo "... Button.s"
	@echo "... CsvReader.o"
	@echo "... CsvReader.i"
	@echo "... CsvReader.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... Level.o"
	@echo "... Level.i"
	@echo "... Level.s"
	@echo "... LevelGenerator.o"
	@echo "... LevelGenerator.i"
	@echo "... LevelGenerator.s"
	@echo "... Mesh.o"
	@echo "... Mesh.i"
	@echo "... Mesh.s"
	@echo "... Model.o"
	@echo "... Model.i"
	@echo "... Model.s"
	@echo "... ModelAnimated.o"
	@echo "... ModelAnimated.i"
	@echo "... ModelAnimated.s"
	@echo "... ObjReader.o"
	@echo "... ObjReader.i"
	@echo "... ObjReader.s"
	@echo "... Obstacle.o"
	@echo "... Obstacle.i"
	@echo "... Obstacle.s"
	@echo "... ObstacleBonus.o"
	@echo "... ObstacleBonus.i"
	@echo "... ObstacleBonus.s"
	@echo "... ObstacleSpawner.o"
	@echo "... ObstacleSpawner.i"
	@echo "... ObstacleSpawner.s"
	@echo "... Particle.o"
	@echo "... Particle.i"
	@echo "... Particle.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... ResourceManager.o"
	@echo "... ResourceManager.i"
	@echo "... ResourceManager.s"
	@echo "... Scene.o"
	@echo "... Scene.i"
	@echo "... Scene.s"
	@echo "... SceneDead.o"
	@echo "... SceneDead.i"
	@echo "... SceneDead.s"
	@echo "... SceneMenu.o"
	@echo "... SceneMenu.i"
	@echo "... SceneMenu.s"
	@echo "... SceneTest.o"
	@echo "... SceneTest.i"
	@echo "... SceneTest.s"
	@echo "... SceneWin.o"
	@echo "... SceneWin.i"
	@echo "... SceneWin.s"
	@echo "... Shader.o"
	@echo "... Shader.i"
	@echo "... Shader.s"
	@echo "... ShaderProgram.o"
	@echo "... ShaderProgram.i"
	@echo "... ShaderProgram.s"
	@echo "... Sprite.o"
	@echo "... Sprite.i"
	@echo "... Sprite.s"
	@echo "... Text.o"
	@echo "... Text.i"
	@echo "... Text.s"
	@echo "... Text3D.o"
	@echo "... Text3D.i"
	@echo "... Text3D.s"
	@echo "... Texture.o"
	@echo "... Texture.i"
	@echo "... Texture.s"
	@echo "... TexturedQuad.o"
	@echo "... TexturedQuad.i"
	@echo "... TexturedQuad.s"
	@echo "... Tile.o"
	@echo "... Tile.i"
	@echo "... Tile.s"
	@echo "... Tilemap.o"
	@echo "... Tilemap.i"
	@echo "... Tilemap.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

