# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fabio/Documents/VJ3D

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fabio/Documents/VJ3D

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fabio/Documents/VJ3D/CMakeFiles /home/fabio/Documents/VJ3D/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fabio/Documents/VJ3D/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CrossyRoad

# Build rule for target.
CrossyRoad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CrossyRoad
.PHONY : CrossyRoad

# fast build rule for target.
CrossyRoad/fast:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/build
.PHONY : CrossyRoad/fast

Button.o: Button.cpp.o

.PHONY : Button.o

# target to build an object file
Button.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Button.cpp.o
.PHONY : Button.cpp.o

Button.i: Button.cpp.i

.PHONY : Button.i

# target to preprocess a source file
Button.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Button.cpp.i
.PHONY : Button.cpp.i

Button.s: Button.cpp.s

.PHONY : Button.s

# target to generate assembly for a file
Button.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Button.cpp.s
.PHONY : Button.cpp.s

Chunk.o: Chunk.cpp.o

.PHONY : Chunk.o

# target to build an object file
Chunk.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Chunk.cpp.o
.PHONY : Chunk.cpp.o

Chunk.i: Chunk.cpp.i

.PHONY : Chunk.i

# target to preprocess a source file
Chunk.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Chunk.cpp.i
.PHONY : Chunk.cpp.i

Chunk.s: Chunk.cpp.s

.PHONY : Chunk.s

# target to generate assembly for a file
Chunk.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Chunk.cpp.s
.PHONY : Chunk.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Game.cpp.s
.PHONY : Game.cpp.s

LvlReader.o: LvlReader.cpp.o

.PHONY : LvlReader.o

# target to build an object file
LvlReader.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/LvlReader.cpp.o
.PHONY : LvlReader.cpp.o

LvlReader.i: LvlReader.cpp.i

.PHONY : LvlReader.i

# target to preprocess a source file
LvlReader.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/LvlReader.cpp.i
.PHONY : LvlReader.cpp.i

LvlReader.s: LvlReader.cpp.s

.PHONY : LvlReader.s

# target to generate assembly for a file
LvlReader.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/LvlReader.cpp.s
.PHONY : LvlReader.cpp.s

Mesh.o: Mesh.cpp.o

.PHONY : Mesh.o

# target to build an object file
Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Mesh.cpp.o
.PHONY : Mesh.cpp.o

Mesh.i: Mesh.cpp.i

.PHONY : Mesh.i

# target to preprocess a source file
Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Mesh.cpp.i
.PHONY : Mesh.cpp.i

Mesh.s: Mesh.cpp.s

.PHONY : Mesh.s

# target to generate assembly for a file
Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Mesh.cpp.s
.PHONY : Mesh.cpp.s

Model.o: Model.cpp.o

.PHONY : Model.o

# target to build an object file
Model.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Model.cpp.o
.PHONY : Model.cpp.o

Model.i: Model.cpp.i

.PHONY : Model.i

# target to preprocess a source file
Model.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Model.cpp.i
.PHONY : Model.cpp.i

Model.s: Model.cpp.s

.PHONY : Model.s

# target to generate assembly for a file
Model.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Model.cpp.s
.PHONY : Model.cpp.s

ObjReader.o: ObjReader.cpp.o

.PHONY : ObjReader.o

# target to build an object file
ObjReader.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObjReader.cpp.o
.PHONY : ObjReader.cpp.o

ObjReader.i: ObjReader.cpp.i

.PHONY : ObjReader.i

# target to preprocess a source file
ObjReader.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObjReader.cpp.i
.PHONY : ObjReader.cpp.i

ObjReader.s: ObjReader.cpp.s

.PHONY : ObjReader.s

# target to generate assembly for a file
ObjReader.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObjReader.cpp.s
.PHONY : ObjReader.cpp.s

Obstacle.o: Obstacle.cpp.o

.PHONY : Obstacle.o

# target to build an object file
Obstacle.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Obstacle.cpp.o
.PHONY : Obstacle.cpp.o

Obstacle.i: Obstacle.cpp.i

.PHONY : Obstacle.i

# target to preprocess a source file
Obstacle.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Obstacle.cpp.i
.PHONY : Obstacle.cpp.i

Obstacle.s: Obstacle.cpp.s

.PHONY : Obstacle.s

# target to generate assembly for a file
Obstacle.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Obstacle.cpp.s
.PHONY : Obstacle.cpp.s

ObstacleCar.o: ObstacleCar.cpp.o

.PHONY : ObstacleCar.o

# target to build an object file
ObstacleCar.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleCar.cpp.o
.PHONY : ObstacleCar.cpp.o

ObstacleCar.i: ObstacleCar.cpp.i

.PHONY : ObstacleCar.i

# target to preprocess a source file
ObstacleCar.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleCar.cpp.i
.PHONY : ObstacleCar.cpp.i

ObstacleCar.s: ObstacleCar.cpp.s

.PHONY : ObstacleCar.s

# target to generate assembly for a file
ObstacleCar.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleCar.cpp.s
.PHONY : ObstacleCar.cpp.s

ObstacleCarSpawner.o: ObstacleCarSpawner.cpp.o

.PHONY : ObstacleCarSpawner.o

# target to build an object file
ObstacleCarSpawner.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleCarSpawner.cpp.o
.PHONY : ObstacleCarSpawner.cpp.o

ObstacleCarSpawner.i: ObstacleCarSpawner.cpp.i

.PHONY : ObstacleCarSpawner.i

# target to preprocess a source file
ObstacleCarSpawner.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleCarSpawner.cpp.i
.PHONY : ObstacleCarSpawner.cpp.i

ObstacleCarSpawner.s: ObstacleCarSpawner.cpp.s

.PHONY : ObstacleCarSpawner.s

# target to generate assembly for a file
ObstacleCarSpawner.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleCarSpawner.cpp.s
.PHONY : ObstacleCarSpawner.cpp.s

ObstacleLillypad.o: ObstacleLillypad.cpp.o

.PHONY : ObstacleLillypad.o

# target to build an object file
ObstacleLillypad.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleLillypad.cpp.o
.PHONY : ObstacleLillypad.cpp.o

ObstacleLillypad.i: ObstacleLillypad.cpp.i

.PHONY : ObstacleLillypad.i

# target to preprocess a source file
ObstacleLillypad.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleLillypad.cpp.i
.PHONY : ObstacleLillypad.cpp.i

ObstacleLillypad.s: ObstacleLillypad.cpp.s

.PHONY : ObstacleLillypad.s

# target to generate assembly for a file
ObstacleLillypad.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleLillypad.cpp.s
.PHONY : ObstacleLillypad.cpp.s

ObstacleTree.o: ObstacleTree.cpp.o

.PHONY : ObstacleTree.o

# target to build an object file
ObstacleTree.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleTree.cpp.o
.PHONY : ObstacleTree.cpp.o

ObstacleTree.i: ObstacleTree.cpp.i

.PHONY : ObstacleTree.i

# target to preprocess a source file
ObstacleTree.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleTree.cpp.i
.PHONY : ObstacleTree.cpp.i

ObstacleTree.s: ObstacleTree.cpp.s

.PHONY : ObstacleTree.s

# target to generate assembly for a file
ObstacleTree.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ObstacleTree.cpp.s
.PHONY : ObstacleTree.cpp.s

Player.o: Player.cpp.o

.PHONY : Player.o

# target to build an object file
Player.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Player.cpp.o
.PHONY : Player.cpp.o

Player.i: Player.cpp.i

.PHONY : Player.i

# target to preprocess a source file
Player.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Player.cpp.i
.PHONY : Player.cpp.i

Player.s: Player.cpp.s

.PHONY : Player.s

# target to generate assembly for a file
Player.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Player.cpp.s
.PHONY : Player.cpp.s

ResourceManager.o: ResourceManager.cpp.o

.PHONY : ResourceManager.o

# target to build an object file
ResourceManager.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ResourceManager.cpp.o
.PHONY : ResourceManager.cpp.o

ResourceManager.i: ResourceManager.cpp.i

.PHONY : ResourceManager.i

# target to preprocess a source file
ResourceManager.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ResourceManager.cpp.i
.PHONY : ResourceManager.cpp.i

ResourceManager.s: ResourceManager.cpp.s

.PHONY : ResourceManager.s

# target to generate assembly for a file
ResourceManager.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ResourceManager.cpp.s
.PHONY : ResourceManager.cpp.s

Scene.o: Scene.cpp.o

.PHONY : Scene.o

# target to build an object file
Scene.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Scene.cpp.o
.PHONY : Scene.cpp.o

Scene.i: Scene.cpp.i

.PHONY : Scene.i

# target to preprocess a source file
Scene.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Scene.cpp.i
.PHONY : Scene.cpp.i

Scene.s: Scene.cpp.s

.PHONY : Scene.s

# target to generate assembly for a file
Scene.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Scene.cpp.s
.PHONY : Scene.cpp.s

SceneMenu.o: SceneMenu.cpp.o

.PHONY : SceneMenu.o

# target to build an object file
SceneMenu.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneMenu.cpp.o
.PHONY : SceneMenu.cpp.o

SceneMenu.i: SceneMenu.cpp.i

.PHONY : SceneMenu.i

# target to preprocess a source file
SceneMenu.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneMenu.cpp.i
.PHONY : SceneMenu.cpp.i

SceneMenu.s: SceneMenu.cpp.s

.PHONY : SceneMenu.s

# target to generate assembly for a file
SceneMenu.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneMenu.cpp.s
.PHONY : SceneMenu.cpp.s

SceneTest.o: SceneTest.cpp.o

.PHONY : SceneTest.o

# target to build an object file
SceneTest.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneTest.cpp.o
.PHONY : SceneTest.cpp.o

SceneTest.i: SceneTest.cpp.i

.PHONY : SceneTest.i

# target to preprocess a source file
SceneTest.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneTest.cpp.i
.PHONY : SceneTest.cpp.i

SceneTest.s: SceneTest.cpp.s

.PHONY : SceneTest.s

# target to generate assembly for a file
SceneTest.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/SceneTest.cpp.s
.PHONY : SceneTest.cpp.s

Shader.o: Shader.cpp.o

.PHONY : Shader.o

# target to build an object file
Shader.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Shader.cpp.o
.PHONY : Shader.cpp.o

Shader.i: Shader.cpp.i

.PHONY : Shader.i

# target to preprocess a source file
Shader.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Shader.cpp.i
.PHONY : Shader.cpp.i

Shader.s: Shader.cpp.s

.PHONY : Shader.s

# target to generate assembly for a file
Shader.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Shader.cpp.s
.PHONY : Shader.cpp.s

ShaderProgram.o: ShaderProgram.cpp.o

.PHONY : ShaderProgram.o

# target to build an object file
ShaderProgram.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ShaderProgram.cpp.o
.PHONY : ShaderProgram.cpp.o

ShaderProgram.i: ShaderProgram.cpp.i

.PHONY : ShaderProgram.i

# target to preprocess a source file
ShaderProgram.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ShaderProgram.cpp.i
.PHONY : ShaderProgram.cpp.i

ShaderProgram.s: ShaderProgram.cpp.s

.PHONY : ShaderProgram.s

# target to generate assembly for a file
ShaderProgram.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/ShaderProgram.cpp.s
.PHONY : ShaderProgram.cpp.s

Sprite.o: Sprite.cpp.o

.PHONY : Sprite.o

# target to build an object file
Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Sprite.cpp.o
.PHONY : Sprite.cpp.o

Sprite.i: Sprite.cpp.i

.PHONY : Sprite.i

# target to preprocess a source file
Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Sprite.cpp.i
.PHONY : Sprite.cpp.i

Sprite.s: Sprite.cpp.s

.PHONY : Sprite.s

# target to generate assembly for a file
Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Sprite.cpp.s
.PHONY : Sprite.cpp.s

Text.o: Text.cpp.o

.PHONY : Text.o

# target to build an object file
Text.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Text.cpp.o
.PHONY : Text.cpp.o

Text.i: Text.cpp.i

.PHONY : Text.i

# target to preprocess a source file
Text.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Text.cpp.i
.PHONY : Text.cpp.i

Text.s: Text.cpp.s

.PHONY : Text.s

# target to generate assembly for a file
Text.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Text.cpp.s
.PHONY : Text.cpp.s

Texture.o: Texture.cpp.o

.PHONY : Texture.o

# target to build an object file
Texture.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Texture.cpp.o
.PHONY : Texture.cpp.o

Texture.i: Texture.cpp.i

.PHONY : Texture.i

# target to preprocess a source file
Texture.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Texture.cpp.i
.PHONY : Texture.cpp.i

Texture.s: Texture.cpp.s

.PHONY : Texture.s

# target to generate assembly for a file
Texture.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/Texture.cpp.s
.PHONY : Texture.cpp.s

TexturedQuad.o: TexturedQuad.cpp.o

.PHONY : TexturedQuad.o

# target to build an object file
TexturedQuad.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/TexturedQuad.cpp.o
.PHONY : TexturedQuad.cpp.o

TexturedQuad.i: TexturedQuad.cpp.i

.PHONY : TexturedQuad.i

# target to preprocess a source file
TexturedQuad.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/TexturedQuad.cpp.i
.PHONY : TexturedQuad.cpp.i

TexturedQuad.s: TexturedQuad.cpp.s

.PHONY : TexturedQuad.s

# target to generate assembly for a file
TexturedQuad.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/TexturedQuad.cpp.s
.PHONY : TexturedQuad.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/CrossyRoad.dir/build.make CMakeFiles/CrossyRoad.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... CrossyRoad"
	@echo "... Button.o"
	@echo "... Button.i"
	@echo "... Button.s"
	@echo "... Chunk.o"
	@echo "... Chunk.i"
	@echo "... Chunk.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... LvlReader.o"
	@echo "... LvlReader.i"
	@echo "... LvlReader.s"
	@echo "... Mesh.o"
	@echo "... Mesh.i"
	@echo "... Mesh.s"
	@echo "... Model.o"
	@echo "... Model.i"
	@echo "... Model.s"
	@echo "... ObjReader.o"
	@echo "... ObjReader.i"
	@echo "... ObjReader.s"
	@echo "... Obstacle.o"
	@echo "... Obstacle.i"
	@echo "... Obstacle.s"
	@echo "... ObstacleCar.o"
	@echo "... ObstacleCar.i"
	@echo "... ObstacleCar.s"
	@echo "... ObstacleCarSpawner.o"
	@echo "... ObstacleCarSpawner.i"
	@echo "... ObstacleCarSpawner.s"
	@echo "... ObstacleLillypad.o"
	@echo "... ObstacleLillypad.i"
	@echo "... ObstacleLillypad.s"
	@echo "... ObstacleTree.o"
	@echo "... ObstacleTree.i"
	@echo "... ObstacleTree.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... ResourceManager.o"
	@echo "... ResourceManager.i"
	@echo "... ResourceManager.s"
	@echo "... Scene.o"
	@echo "... Scene.i"
	@echo "... Scene.s"
	@echo "... SceneMenu.o"
	@echo "... SceneMenu.i"
	@echo "... SceneMenu.s"
	@echo "... SceneTest.o"
	@echo "... SceneTest.i"
	@echo "... SceneTest.s"
	@echo "... Shader.o"
	@echo "... Shader.i"
	@echo "... Shader.s"
	@echo "... ShaderProgram.o"
	@echo "... ShaderProgram.i"
	@echo "... ShaderProgram.s"
	@echo "... Sprite.o"
	@echo "... Sprite.i"
	@echo "... Sprite.s"
	@echo "... Text.o"
	@echo "... Text.i"
	@echo "... Text.s"
	@echo "... Texture.o"
	@echo "... Texture.i"
	@echo "... Texture.s"
	@echo "... TexturedQuad.o"
	@echo "... TexturedQuad.i"
	@echo "... TexturedQuad.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

